### ISSUE TITLE
Tidy up VC names

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/vice-counties#3]
It's been highlighted that the three versions of the VC boundaries have slightly differing names for some individual VCs. This relates to a broader issue which is that appears to be no agreed standard for VC names, and all published sources vary in some respects. However, we need to make sensible choices and ensure that we are internally consistent.

@kitenetter to review the highlighted mismatches and propose a set of names to harmonise across all uses.

**Comment by DavidRoy** [comment]
I agree, it would be good to have 'BRC' list of VC names...

**Comment by burkmarr** [comment]
Once names are defined, @burkmarr update the three layers (https://github.com/BiologicalRecordsCentre/vice-counties) and also implement the reassignment of Sule Skerry and Sule Stack to Orkneys from Outer Hebrides (to which they are currently incorrectly assigned). Then raise an issue to update Warehouse.

**Comment by kitenetter** [comment]
Definitive list of names is here:
[BRC vice-county name list 2020_11_02.xlsx](https://github.com/BiologicalRecordsCentre/vice-counties/files/5477317/BRC.vice-county.name.list.2020_11_02.xlsx)

That list should be applied to each of the three VC layers (MLWM, 3-mile and 12-mile). The vice-county names in iRecord should also be updated.

I have edited the [list on the BRC website](https://www.brc.ac.uk/article/british-vice-counties) to match.

**Comment by burkmarr** [comment]
@kitenetter I've updated the three shapefiles and opened an issue to update the Warehouse (https://github.com/BiologicalRecordsCentre/iRecord/issues/945). Shall I add the definitive spreadsheet of names to the repo?

**Comment by kitenetter** [comment]
I don't see any reason not to do that.

**Comment by burkmarr** [comment]
Okay that's done.
